### ISSUE TITLE
Missing Makefile.in in CCache

### ISSUE THREAD

**Issue by cbo1964** [CartoDB/mobile-swig#1]
Hi,

trying to compile on Mac OS X.
autogen.sh DONE
Tools/pcre-build.sh DONE
./configure 
I get this error
config.status: error: cannot find input file: `Makefile.in'
configure: error: ./configure failed for CCache

Checking, seems taht makefile.am is missing in CCache subdirectory

Any idea ?

Thanks
Regards
Claudio

**Comment by gimkim** [comment]
Same issue.

**Comment by mtehver** [comment]
Sorry for the long-delayed answer, somehow we were not notified of the submitted issue.

This error message should be actually harmless. You can run `make` after the error. Nevertheless, if you do not have CCache installed, then you should simply run configure script as follows:

```
./configure --disable-ccache
```

and you will not get the message.
